name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 安装Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装测试工具
        run: pip install pytest pytest-cov coverage

      - name: 执行测试和覆盖率检查
        run: |
          pytest tests/ --cov=src --cov-report=term --cov-report=html:docs/coverage/html --cov-report=xml:docs/coverage/coverage.xml
          # 生成 XML 和 HTML 双格式报告

      - name: 上传HTML报告
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: docs/coverage/html

      - name: 上传到Coveralls (需配置Token)
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_SECRET }}
          path-to-lcov: docs/coverage/coverage.xml  # 显式指定 XML 文件路径
