<<<<<<< HEAD
name: Build and Test

on: [push]  # 每次提交代码自动运行

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub提供的虚拟机环境

    steps:
      # 步骤1：获取代码
      - name: 检出代码仓库
        uses: actions/checkout@v4

      # 步骤2：安装Python
=======
name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

>>>>>>> f46920c0eedda075868c90a311f49cc1efec7493
      - name: 安装Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

<<<<<<< HEAD
      # 步骤3：安装依赖库
      - name: 安装测试工具
        run: pip install pytest pytest-cov

      # 步骤4：运行测试 + 生成报告
      - name: 执行测试和覆盖率检查
        run: |
          pytest tests/ --cov=src --cov-report=html:docs/coverage/html  # 增加子目录隔离

      # 步骤5：上传报告供下载
      - name: 上传覆盖率报告
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: docs/coverage
=======
      - name: 安装依赖
        run: pip install pytest pytest-cov

      - name: 执行测试并生成覆盖率报告
        run: |  # 注意：以下内容有缩进！
          pytest tests/ --cov=src --cov-report=term --cov-report=xml:docs/coverage/coverage.xml
          mkdir -p docs/coverage
          [ -f coverage.xml ] && mv coverage.xml docs/coverage/  # 处理可能的路径差异

      - name: 上传到Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_SECRET }}
          path-to-lcov: docs/coverage/coverage.xml
>>>>>>> f46920c0eedda075868c90a311f49cc1efec7493

